main:   Update.class PA3.class ReadInput.class Node.class Game.class

Update.class:   Update.java
        javac Update.java

PA3.class: PA3.java
        javac PA3.java

ReadInput.class: ReadInput.java
        javac ReadInput.java

Node.class: Node.java
        javac Node.java

Game.class: Game.java
        javac Game.java
